name: Sincronizar Partidos

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-matches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Instalar pnpm manualmente
        run: npm install -g pnpm@9

      - name: Instalar dependencias
        # Usamos --force para ignorar cualquier conflicto y --no-frozen-lockfile
        run: pnpm install --force --no-frozen-lockfile

      - name: Ejecutar script de actualización
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: pnpm --filter @workspace/scripts run update-matches